app = "dream-job-reality-check-api"
primary_region = "atl"

[build]
  dockerfile = "Dockerfile"

[env]
  SERVER_PORT = "8080"
  CORS_ORIGIN = "https://dream-job-reality-check.vercel.app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/health"