// src/mockOccupations.js
export const mockOccupations = [
  "Accountants and Auditors",
  "Actors",
  "Actuaries",
  "Aerospace Engineers",
  "Agricultural Engineers",
  "Anesthesiologists",
  "Architects, Except Landscape and Naval",
  "Biomedical Engineers",
  "Chefs and Head Cooks",
  "Chemical Engineers",
  "Civil Engineers",
  "Computer Programmers",
  "Data Scientists",
  "Database Administrators",
  "Dentists, General",
  "Designers, All Other",
  "Elementary School Teachers",
  "Financial Analysts",
  "Firefighters",
  "Graphic Designers",
  "Lawyers",
  "Marketing Managers",
  "Mechanical Engineers",
  "Musicians and Singers",
  "Network and Computer Systems Administrators",
  "Pharmacists",
  "Photographers",
  "Physician Assistants",
  "Police and Sheriff's Patrol Officers",
  "Registered Nurses",
  "Software Developers",
  "Surgeons, Except Ophthalmologists",
  "Veterinarians",
  "Web Developers",
];